Hash search memcache key to limit key length
The default memcached server's max key length is 250 characters.  If a
user's search query is really long, archive throws this exception:

```
ERROR:waitress:Exception when serving /search
Traceback (most recent call last):
  File "/var/cnx/venvs/archive/local/lib/python2.7/site-packages/waitress/channel.py", line 338, in service
    task.service()
  File "/var/cnx/venvs/archive/local/lib/python2.7/site-packages/waitress/task.py", line 169, in service
    self.execute()
  File "/var/cnx/venvs/archive/local/lib/python2.7/site-packages/waitress/task.py", line 399, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "/var/cnx/venvs/archive/local/lib/python2.7/site-packages/paste/deploy/config.py", line 291, in __call__
    return self.app(environ, start_response)
  File "/var/cnx/venvs/archive/local/lib/python2.7/site-packages/pyramid/router.py", line 223, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/var/cnx/venvs/archive/local/lib/python2.7/site-packages/pyramid/router.py", line 198, in invoke_subrequest
    response = handle_request(request)
  File "/var/cnx/venvs/archive/local/lib/python2.7/site-packages/pyramid/tweens.py", line 20, in excview_tween
    response = handler(request)
  File "/var/cnx/venvs/archive/local/lib/python2.7/site-packages/pyramid/router.py", line 145, in handle_request
    view_name
  File "/var/cnx/venvs/archive/local/lib/python2.7/site-packages/pyramid/view.py", line 541, in _call_view
    response = view_callable(context, request)
  File "/var/cnx/venvs/archive/local/lib/python2.7/site-packages/pyramid/config/views.py", line 327, in attr_view
    return view(context, request)
  File "/var/cnx/venvs/archive/local/lib/python2.7/site-packages/pyramid/config/views.py", line 303, in predicate_wrapper
    return view(context, request)
  File "/var/cnx/venvs/archive/local/lib/python2.7/site-packages/pyramid/config/views.py", line 384, in viewresult_to_response
    result = view(context, request)
  File "/var/cnx/venvs/archive/local/lib/python2.7/site-packages/pyramid/config/views.py", line 506, in _requestonly_view
    response = view(request)
  File "/var/cnx/venvs/archive/local/lib/python2.7/site-packages/cnxarchive/views.py", line 791, in search
    nocache=params.get('nocache', '').lower() == 'true')
  File "/var/cnx/venvs/archive/local/lib/python2.7/site-packages/cnxarchive/cache.py", line 52, in search
    search_results = mc.get(mc_search_key)
  File "/var/cnx/venvs/archive/local/lib/python2.7/site-packages/memcache.py", line 898, in get
    return self._get('get', key)
  File "/var/cnx/venvs/archive/local/lib/python2.7/site-packages/memcache.py", line 847, in _get
    self.check_key(key)
  File "/var/cnx/venvs/archive/local/lib/python2.7/site-packages/memcache.py", line 1059, in check_key
    % self.server_max_key_length)
MemcachedKeyLengthError: Key length is > 250
```

To avoid this error, hash the search query using sha1 so the memcache
key stays the same length.

Close #517